version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    restart: always

  fgstest:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/fgstest/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: