# Generated by Django 4.1 on 2022-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=70)),
                ('postal_code', models.CharField(blank=True, default='', max_length=11)),
                ('country', models.CharField(blank=True, default='', max_length=10)),
                ('federal_district', models.CharField(blank=True, default='', max_length=20)),
                ('region_type', models.CharField(blank=True, default='', max_length=11)),
                ('region', models.CharField(blank=True, default='', max_length=40)),
                ('area_type', models.CharField(blank=True, default='', max_length=10)),
                ('area', models.CharField(blank=True, default='', max_length=30)),
                ('city_type', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('settlement_type', models.CharField(blank=True, default='', max_length=20)),
                ('settlement', models.CharField(blank=True, default='', max_length=20)),
                ('kladr_id', models.CharField(blank=True, default='', max_length=20)),
                ('fias_id', models.CharField(blank=True, default='', max_length=36)),
                ('fias_level', models.CharField(blank=True, default='', max_length=20)),
                ('capital_marker', models.CharField(blank=True, default='', max_length=20)),
                ('okato', models.CharField(blank=True, default='', max_length=20)),
                ('oktmo', models.CharField(blank=True, default='', max_length=20)),
                ('tax_office', models.CharField(blank=True, default='', max_length=20)),
                ('timezone', models.CharField(blank=True, default='', max_length=20)),
                ('geo_lat', models.CharField(blank=True, default='', max_length=20)),
                ('geo_lon', models.CharField(blank=True, default='', max_length=20)),
                ('population', models.CharField(blank=True, default='', max_length=20)),
                ('foundation_year', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
